package com.transport.simulator.ticketing.qr;

public enum TicketQrVerificationFailure {
    MALFORMED_QR,
    UNSUPPORTED_VERSION,
    INVALID_HEADER,
    UNTRUSTED_KEY,
    INVALID_SIGNATURE,
    INVALID_PAYLOAD,
    NOT_YET_VALID,
    EXPIRED,
    CREDENTIAL_NOT_FOUND,
    CREDENTIAL_REVOKED,
    CREDENTIAL_SUPERSEDED,
    CREDENTIAL_INCONSISTENT,
    VERIFICATION_NOT_CONFIGURED
}
