export type LogSeverity = 'DEBUG' | 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';
export type LogOrigin = 'ADMINISTRATION' | 'DEVICE_SIMULATION' | 'MQTT';
export type DeviceEventSource = 'SIMULATED' | 'REAL' | 'ADMINISTRATIVE';
export type TicketProductType = 'SINGLE_TRIP' | 'MULTI_TRIP' | 'TIME_PASS' | 'SMART_BALANCE';

export type DeviceEventType =
  | 'DEVICE_ONLINE'
  | 'DEVICE_OFFLINE'
  | 'DEVICE_STATUS_CHANGED'
  | 'DEVICE_ERROR'
  | 'DEVICE_MAINTENANCE_STARTED'
  | 'DEVICE_MAINTENANCE_FINISHED'
  | 'TICKET_PURCHASE_REQUESTED'
  | 'TICKET_PURCHASE_COMPLETED'
  | 'TICKET_PURCHASE_FAILED'
  | 'COMPENSATORY_TICKET_ISSUANCE_REQUESTED'
  | 'COMPENSATORY_TICKET_ISSUED'
  | 'QR_TICKET_GENERATED'
  | 'QR_TICKET_SCANNED'
  | 'VALIDATION_REQUESTED'
  | 'VALIDATION_ACCEPTED'
  | 'VALIDATION_REJECTED'
  | 'VALIDATION_FAILED';
