package com.transport.simulator.enums;

public enum DeviceEventType {
    DEVICE_ONLINE,
    DEVICE_OFFLINE,
    DEVICE_STATUS_CHANGED,
    DEVICE_ERROR,
    DEVICE_MAINTENANCE_STARTED,
    DEVICE_MAINTENANCE_FINISHED,
    TICKET_PURCHASE_REQUESTED,
    TICKET_PURCHASE_COMPLETED,
    TICKET_PURCHASE_FAILED,
    COMPENSATORY_TICKET_ISSUED,
    QR_TICKET_GENERATED,
    QR_TICKET_SCANNED,
    VALIDATION_REQUESTED,
    VALIDATION_ACCEPTED,
    VALIDATION_REJECTED,
    VALIDATION_FAILED
}
